baseURL = "http://techdesk.pbdesk.com/"
languageCode = "en-us"
title = "TechDesk"
theme = "techdesk"
metaDataFormat = "yaml"

[params]
  editURL = "#"
  description = "TechDesk - from the desk of Pinal Bhatt"
  author = "Pinal Bhatt"
  showVisitedLinks = true

[outputs]
home = [ "HTML", "RSS", "JSON"]  
